/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_atomone_Secureinspect_SecureApi */

#ifndef _Included_com_atomone_Secureinspect_SecureApi
#define _Included_com_atomone_Secureinspect_SecureApi
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    debugCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_debugCheck
        (JNIEnv *, jobject);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    rootCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_rootCheck
        (JNIEnv *, jobject);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    rootCheck
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_injectCheck
        (JNIEnv *, jobject);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    emulatorCheck
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_emulatorCheck
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    signPackageCheck
 * Signature: (Ljava/lang/Object;Lcom/atomone/Secureinspect/IVerifyListener;)I
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_signPackageCheck
        (JNIEnv *, jobject, jobject);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    getRemoteAppSign
 * Signature: (Ljava/lang/Object;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_atomone_Secureinspect_SecureApi_getRemoteAppSign
        (JNIEnv *, jobject, jobject, jstring);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    isRunInVa
 * Signature: ()Z
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_isRunInVa
        (JNIEnv *, jobject);

/*
 * Class:     com_atomone_Secureinspect_SecureApi
 * Method:    isMultiOpen
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_atomone_Secureinspect_SecureApi_isMultiOpen
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
